language: python

install: skip

services:
    - docker

script:
    - "docker build -t jbflow93/user-wishlist-app ."
after_success:
    - "echo \"$DOCKER_PASSWORD\" | docker login -u \"$DOCKER_ID\" --password-stdin"
    - "docker push jbflow93/user-wishlist-app"

deploy:
  region: us-east-2
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket_name: multi-wishlist-app
  bucket_path: docker
  env: Jbuserwishlistapp-env
  provider: elasticbeanstalk
  true:
    branch: Multi-cont-app